# Generated by Django 4.1 on 2022-09-04 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('button', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/Sliders/%Y/%m')),
            ],
        ),
    ]
