# Generated by Django 4.1 on 2022-09-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='button',
            new_name='button_text',
        ),
        migrations.RenameField(
            model_name='slider',
            old_name='title',
            new_name='headline',
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='media/sliders/%Y/%m'),
        ),
    ]
