# Generated by Django 4.1 on 2022-09-04 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_rename_button_slider_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
