# Generated by Django 4.1 on 2022-09-09 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtubers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('subs_count', models.IntegerField()),
                ('category', models.CharField(choices=[('coding', 'coding'), ('vlogs', 'vlogs'), ('education', 'education'), ('reviews', 'reviews')], max_length=255)),
                ('city', models.CharField(choices=[('Delhi', 'Delhi'), ('Jaipur', 'Jaipur'), ('Mumbai', 'Mumbai'), ('Gurugram', 'Gurugram')], max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('video', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/youtubers/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 9, 20, 21, 54, 201096))),
            ],
        ),
    ]
