# Generated by Django 4.1.1 on 2022-09-09 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_alter_youtuber_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 9, 20, 44, 23, 824796)),
        ),
    ]
