# Generated by Django 4.1.1 on 2022-09-10 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0006_youtuber_crew_youtuber_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 16, 34, 6, 369119)),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], default='solo', max_length=50),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
