# Generated by Django 4.1.1 on 2022-09-10 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0007_alter_youtuber_created_date_alter_youtuber_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 10, 16, 34, 56, 697855)),
        ),
    ]
