# Generated by Django 4.1.1 on 2022-09-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0013_alter_youtuber_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 12, 22, 43, 57, 938192)),
        ),
    ]
