# Generated by Django 4.1.2 on 2022-10-09 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0014_alter_youtuber_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 9, 14, 35, 55, 438919)),
        ),
    ]
